Fix SyntaxError
It had an extra closing parenthesis causing SyntaxError.

````
File "scraper.py", line 437
    for (i, platform) in enumerate(ES_systems)):
                                              ^
SyntaxError: invalid syntax
````